server:
  port: 8080


spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/userService
    username: root
    password: Hunter@4343
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/users/**
            - id: news-management-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/news/**






