spring:
  application:
    name: news-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/newsService
    username: root
    password: Hunter@4343
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: java-service
      auto-offset-reset: earliest


server:
  port: 8082