spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/userService
    username: root
    password: Hunter@4343
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true



server:
  port: 8081