name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run:
          mvn -f api-gateway/pom.xml clean install
          mvn -f fact-check-service/pom.xml clean install
          mvn -f news-management-service/pom.xml clean install -DskipTests
          mvn -f source-credibility-service/pom.xml clean install
          mvn -f user-service/pom.xml clean install -DskipTests